models:
- name: loan_application_funnel
  description: This model aggregates loan application data to provide insights into
    the loan application process across different banks and loan types. It calculates
    key metrics such as the number of applications submitted, approved, rejected,
    and under review, as well as approval rates, total and average requested and approved
    amounts, and average decision turnaround time. This information is useful for
    analyzing the efficiency and effectiveness of the loan application process.
  columns:
  - name: bank_id
    description: The unique identifier for the bank.
    data_tests:
      - not_null
  - name: loan_type
    description: The type of loan applied for.
    data_tests:
      - not_null
  - name: year
    description: The year the loan application was submitted.
    data_tests:
      - not_null
  - name: applications_submitted
    description: The total number of loan applications submitted.
  - name: applications_approved
    description: The total number of loan applications approved.
  - name: applications_rejected
    description: The total number of loan applications rejected.
  - name: applications_under_review
    description: The total number of loan applications still under review.
  - name: approval_rate_pct
    description: The percentage of loan applications that were approved.
  - name: total_requested_amount
    description: The total amount of money requested in loan applications.
  - name: total_approved_amount
    description: The total amount of money approved in loan applications.
  - name: avg_requested_amount
    description: The average amount of money requested in loan applications.
  - name: avg_approved_amount
    description: The average amount of money approved in loan applications.
  - name: avg_decision_turnaround_days
    description: The average number of days taken to make a decision on loan applications.